### ISSUE TITLE
make编译失败

### ISSUE THREAD

**Issue by h1ac0k** [XiaoMi/Gaea#50]
编译代码为master上现拉的代码，具体的报错信息如下所示：

**编译信息：**
[root@ip-10-0-21-222 Gaea]# make
cd parser && make && cd ..
make[1]: 进入目录“/data/Gaea/parser”
make parser
make[2]: 进入目录“/data/Gaea/parser”
./goyacc -o /dev/null parser.y
Parse table entries: 946812 of 2383712, x 16 bits == 1893624 bytes
./goyacc -o parser.go parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; exit 1;}}'
rm -f y.output
make[2]: 离开目录“/data/Gaea/parser”
#@echo "gofmt (simplify)"
#@ gofmt -s -l -w . 2>&1 | awk '{print} END{if(NR>0) {exit 1}}'
make[1]: 离开目录“/data/Gaea/parser”
go build -o /data/Gaea/bin/gaea -pkgdir=/root/go/pkg/linux_amd64 -ldflags "-extldflags -static  -X github.com/XiaoMi/Gaea/core.buildVersion=666d59e9f7ea563733299d97260ee43307881d70-dirty -X github.com/XiaoMi/Gaea/core.buildGitRevision=666d59e9f7ea563733299d97260ee43307881d70-dirty -X github.com/XiaoMi/Gaea/core.buildUser=root -X github.com/XiaoMi/Gaea/core.buildHost=ip-10-0-21-222.ap-east-1.compute.internal -X github.com/XiaoMi/Gaea/core.buildStatus=Modified -X github.com/XiaoMi/Gaea/core.buildTime=2019-09-16--08:21:47" github.com/XiaoMi/Gaea/cmd/gaea
go: downloading github.com/gin-contrib/gzip v0.0.1
go: downloading github.com/gin-gonic/gin v1.3.0
go: downloading github.com/go-ini/ini v1.42.0
go: downloading github.com/pingcap/tipb v0.0.0-20190226124958-833c2ffd2fe7
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/pingcap/errors v0.11.1
go: downloading github.com/coreos/etcd v3.3.13+incompatible
go: downloading github.com/prometheus/client_golang v0.9.2
go: extracting github.com/gin-contrib/gzip v0.0.1
go: downloading github.com/cznic/mathutil v0.0.0-20181122101859-297441e03548
go: extracting github.com/pingcap/errors v0.11.1
go: extracting github.com/emirpasic/gods v1.12.0
go: extracting github.com/cznic/mathutil v0.0.0-20181122101859-297441e03548
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20190321074620-2f0d2b0e0001
go: extracting github.com/prometheus/client_golang v0.9.2
go: downloading github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: extracting github.com/go-ini/ini v1.42.0
go: extracting github.com/pingcap/tipb v0.0.0-20190226124958-833c2ffd2fe7
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/golang/protobuf v1.2.0
go: downloading github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: extracting github.com/gin-gonic/gin v1.3.0
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading gopkg.in/yaml.v2 v2.2.1
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f
go: extracting github.com/remyoudompheng/bigfft v0.0.0-20190321074620-2f0d2b0e0001
go: downloading gopkg.in/go-playground/validator.v8 v8.18.2
go: extracting github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: extracting github.com/mattn/go-isatty v0.0.7
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: extracting github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: downloading github.com/gin-contrib/sse v0.0.0-20190301062529-5545eab6dad3
go: extracting gopkg.in/go-playground/validator.v8 v8.18.2
go: extracting gopkg.in/yaml.v2 v2.2.1
go: extracting github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: extracting github.com/golang/protobuf v1.2.0
go: extracting github.com/gin-contrib/sse v0.0.0-20190301062529-5545eab6dad3
go: extracting github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/coreos/etcd v3.3.13+incompatible
go: extracting golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/json-iterator/go v1.1.6
go: downloading github.com/coreos/go-semver v0.2.0
go: extracting github.com/coreos/go-semver v0.2.0
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/json-iterator/go v1.1.6
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/go-ini/ini v1.42.0
go: finding github.com/coreos/etcd v3.3.13+incompatible
go: finding github.com/json-iterator/go v1.1.6
go: finding github.com/pingcap/errors v0.11.1
go: finding github.com/coreos/go-semver v0.2.0
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/prometheus/client_golang v0.9.2
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/gin-contrib/gzip v0.0.1
go: finding github.com/gin-gonic/gin v1.3.0
go: finding github.com/emirpasic/gods v1.12.0
go: finding github.com/cznic/mathutil v0.0.0-20181122101859-297441e03548
go: finding github.com/pingcap/tipb v0.0.0-20190226124958-833c2ffd2fe7
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/remyoudompheng/bigfft v0.0.0-20190321074620-2f0d2b0e0001
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: finding github.com/gin-contrib/sse v0.0.0-20190301062529-5545eab6dad3
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/mattn/go-isatty v0.0.7
go: finding github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f
go: finding gopkg.in/go-playground/validator.v8 v8.18.2
go: finding gopkg.in/yaml.v2 v2.2.1
go build -o /data/Gaea/bin/gaea-cc -pkgdir=/root/go/pkg/linux_amd64 -ldflags "-extldflags -static  -X github.com/XiaoMi/Gaea/core.buildVersion=666d59e9f7ea563733299d97260ee43307881d70-dirty -X github.com/XiaoMi/Gaea/core.buildGitRevision=666d59e9f7ea563733299d97260ee43307881d70-dirty -X github.com/XiaoMi/Gaea/core.buildUser=root -X github.com/XiaoMi/Gaea/core.buildHost=ip-10-0-21-222.ap-east-1.compute.internal -X github.com/XiaoMi/Gaea/core.buildStatus=Modified -X github.com/XiaoMi/Gaea/core.buildTime=2019-09-16--08:22:30" github.com/XiaoMi/Gaea/cmd/gaea-cc
go test -coverprofile=.coverage.out ./...
go: downloading github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
go: extracting github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
go: finding github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
ok  	github.com/XiaoMi/Gaea/backend	0.021s	coverage: 3.4% of statements
?   	github.com/XiaoMi/Gaea/cc	[no test files]
?   	github.com/XiaoMi/Gaea/cc/proxy	[no test files]
?   	github.com/XiaoMi/Gaea/cc/service	[no test files]
ok  	github.com/XiaoMi/Gaea/cmd/gaea	0.006s	coverage: 14.0% of statements
?   	github.com/XiaoMi/Gaea/cmd/gaea-cc	[no test files]
?   	github.com/XiaoMi/Gaea/core	[no test files]
?   	github.com/XiaoMi/Gaea/core/errors	[no test files]
?   	github.com/XiaoMi/Gaea/log	[no test files]
?   	github.com/XiaoMi/Gaea/log/xlog	[no test files]
ok  	github.com/XiaoMi/Gaea/models	0.004s	coverage: 22.2% of statements
ok  	github.com/XiaoMi/Gaea/models/etcd	0.002s	coverage: 4.4% of statements
?   	github.com/XiaoMi/Gaea/models/file	[no test files]
ok  	github.com/XiaoMi/Gaea/mysql	0.011s	coverage: 34.3% of statements
ok  	github.com/XiaoMi/Gaea/parser	0.404s	coverage: 84.1% of statements
ok  	github.com/XiaoMi/Gaea/parser/ast	0.149s	coverage: 57.1% of statements
ok  	github.com/XiaoMi/Gaea/parser/auth	0.027s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/XiaoMi/Gaea/parser/format	0.029s	coverage: 81.3% of statements
ok  	github.com/XiaoMi/Gaea/parser/model	0.025s	coverage: 53.6% of statements
ok  	github.com/XiaoMi/Gaea/parser/opcode	0.002s	coverage: 55.6% of statements
?   	github.com/XiaoMi/Gaea/parser/stmtctx	[no test files]
ok  	github.com/XiaoMi/Gaea/parser/terror	0.012s	coverage: 75.9% of statements
ok  	github.com/XiaoMi/Gaea/parser/tidb-types	0.031s	coverage: 67.3% of statements
ok  	github.com/XiaoMi/Gaea/parser/tidb-types/json	0.034s	coverage: 81.4% of statements
ok  	github.com/XiaoMi/Gaea/parser/tidb-types/parser_driver	0.014s	coverage: 24.7% of statements
?   	github.com/XiaoMi/Gaea/parser/types	[no test files]
--- FAIL: TestSelectKingshardDateYear (0.01s)
    --- FAIL: TestSelectKingshardDateYear/select_*_from_tbl_ks_year_where_create_time_<=_1388505600 (0.00s)
        plan_test.go:110: not equal, expect: map[slice-0:map[db_ks:[SELECT * FROM `tbl_ks_year_2014` WHERE `create_time`<=1388505600]]], actual: map[]
    --- FAIL: TestSelectKingshardDateYear/select_*_from_tbl_ks_year_where_create_time_<=_1388505600#01 (0.00s)
        plan_test.go:110: not equal, expect: map[slice-0:map[db_ks:[SELECT * FROM `tbl_ks_year_2014` WHERE `create_time`<=1388505600]]], actual: map[]
    --- FAIL: TestSelectKingshardDateYear/select_*_from_tbl_ks_year_where_create_time_>=_1514736000 (0.00s)
        plan_test.go:110: not equal, expect: map[slice-1:map[db_ks:[SELECT * FROM `tbl_ks_year_2018` WHERE `create_time`>=1514736000 SELECT * FROM `tbl_ks_year_2019` WHERE `create_time`>=1514736000]]], actual: map[slice-0:map[db_ks:[SELECT * FROM `tbl_ks_year_2017` WHERE `create_time`>=1514736000]] slice-1:map[db_ks:[SELECT * FROM `tbl_ks_year_2018` WHERE `create_time`>=1514736000 SELECT * FROM `tbl_ks_year_2019` WHERE `create_time`>=1514736000]]]
    --- FAIL: TestSelectKingshardDateYear/select_*_from_tbl_ks_year_where_create_time_>=_1577808000 (0.00s)
        plan_test.go:110: not equal, expect: map[], actual: map[slice-1:map[db_ks:[SELECT * FROM `tbl_ks_year_2019` WHERE `create_time`>=1577808000]]]
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 377 [running]:
testing.tRunner.func1(0xc000490600)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xa517e0, 0xc0000262a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/XiaoMi/Gaea/proxy/plan.checkSQLs.func1(0xc0004a4390, 0xc000020750, 0xc00000e7c0)
	/data/Gaea/proxy/plan/plan_test.go:151 +0x38a
github.com/XiaoMi/Gaea/proxy/plan.checkSQLs(0xc0004a4390, 0xc000020750, 0xa941c5)
	/data/Gaea/proxy/plan/plan_test.go:160 +0x40
github.com/XiaoMi/Gaea/proxy/plan.getTestFunc.func1(0xc000490600)
	/data/Gaea/proxy/plan/plan_test.go:109 +0x408
testing.tRunner(0xc000490600, 0xc000270fc0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/XiaoMi/Gaea/proxy/plan	0.306s
ok  	github.com/XiaoMi/Gaea/proxy/router	0.017s	coverage: 57.4% of statements
?   	github.com/XiaoMi/Gaea/proxy/sequence	[no test files]
ok  	github.com/XiaoMi/Gaea/proxy/server	0.015s	coverage: 3.2% of statements
ok  	github.com/XiaoMi/Gaea/stats	0.006s	coverage: 69.6% of statements
ok  	github.com/XiaoMi/Gaea/stats/prometheus	0.036s	coverage: 97.1% of statements
ok  	github.com/XiaoMi/Gaea/util	10.311s	coverage: 49.3% of statements
ok  	github.com/XiaoMi/Gaea/util/bucketpool	0.054s	coverage: 93.9% of statements
ok  	github.com/XiaoMi/Gaea/util/cache	0.001s	coverage: 98.1% of statements
ok  	github.com/XiaoMi/Gaea/util/crypto	0.001s	coverage: 69.7% of statements
ok  	github.com/XiaoMi/Gaea/util/hack	0.001s	coverage: 55.0% of statements
?   	github.com/XiaoMi/Gaea/util/math	[no test files]
ok  	github.com/XiaoMi/Gaea/util/requests	0.002s	coverage: 48.5% of statements
ok  	github.com/XiaoMi/Gaea/util/sync2	0.027s	coverage: 60.3% of statements
?   	github.com/XiaoMi/Gaea/util/testleak	[no test files]
ok  	github.com/XiaoMi/Gaea/util/timer	0.702s	coverage: 96.2% of statements
FAIL
make: *** [test] 错误 1

**系统环境：**

[root@ip-10-0-21-222 mod]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Golang版本**
[root@ip-10-0-21-222 Gaea]# go version
go version go1.13 linux/amd64

同样的代码在Mac下可以正常通过，功能测试也正常

**Comment by h1ac0k** [comment]
已解决，直接make build 就可以生成二进制文件了
